Fix fall-through if upload retry fails more than 5 times

diff --git a/impake b/impake
--- a/impake
+++ b/impake
@@ -325,12 +325,13 @@ for f in $files; do
 	for t in 1 2 3 4 5 6; do
 		response=$(curl -F "file=@${f}" "${storage_url}/?${expires_parameter}=${opt_expire_arg}")
 		test "$(echo "$response" | jq -r '.success'  2>/dev/null)" = 'true' && break
-		test $t -eq 6 || echo "Upload failed, retrying: ${t}/5" 1>&2
-		sleep "$upload_failure_throttle"
+		if [ $t -lt 6 ]; then
+			echo "Upload failed, retrying: ${t}/5" 1>&2
+			sleep "$upload_failure_throttle"
+		else
+			fail 'Aborting after 5 attempts.'
+		fi
 	done
-	if [ $? -gt 0 ]; then
-		fail 'Aborting after 5 attempts.'
-	fi
 	urls="${urls:-}$(echo "$response" | jq -r '.link') "
 	expiry=$(echo "$response" | jq -r '.expiry')
 done
