Check for presence of extra tools we need

diff --git a/impake b/impake
--- a/impake
+++ b/impake
@@ -12,6 +12,13 @@ if [ $# -lt 1 ]; then
 	exit 1
 fi
 
+for tool in 7z jq curl; do
+	which "$tool" >/dev/null 2>&1 || missing="${missing:-}${tool} "
+done
+if [ -n "${missing:-}" ]; then
+	echo "Missing: ${missing% }. Aborting." 1>&2
+	exit 1
+fi
 
 # BSD
 if mktemp -d -u -t "$me" >/dev/null 2>&1; then
